### ISSUE TITLE
Disallow override CaptureAgent.py functions (need python3.8)

### ISSUE THREAD

**Issue by nirlipo** [AI4EDUC/pacman-contest-agent#19]
See this post on the use of the decorator `final` for python3.8

https://stackoverflow.com/a/58939735

Currently myTeam.py can override `makeObservation` and access to the full state, which goes against the rules of the game.

We should at least create some scripts to make sure teams are not doing so at the moment. Grep over myTeam.py looking for `makeObservation`? For example, I know there's no cheating in my competition by checking in the folder containing all the teams:

```
grep -r 'def makeObservation'
deepfish/capture.py:  def makeObservation(self, index):
pac/capture.py:  def makeObservation(self, index):
pacamon/capture.py:  def makeObservation(self, index):
funpacman/capture.py:  def makeObservation(self, index):
a-team/capture.py:  def makeObservation(self, index):
tang/capture.py:  def makeObservation(self, index):
grape/capture.py:  def makeObservation(self, index):
house-tangaryen/capture.py:  def makeObservation(self, index):
ypz/capture.py:  def makeObservation(self, index):
pac-superman/capture.py:  def makeObservation(self, index):
triplez/capture.py:  def makeObservation(self, index):
91-ai-club/capture.py:  def makeObservation(self, index):
pachub/capture.py:  def makeObservation(self, index):
awful-go/capture.py:  def makeObservation(self, index):
```

and hence the following command should return only the teams cheating:

```
grep -r 'def makeObservation' | grep myTeam.py
```

**Comment by ssardina** [comment]
BTW, the solution to this is:

1. We make frozen whatever we can as we go. I did that with the above variable using `frozendict`. This will catch some cases when they modify the variable. They can always assign a new value.
2. We monitor for failing cases.
3. Explicitly state one must not tamper with the infrastructure; can read but never write without permission.
